default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: template_development

test:
  <<: *default
  database: template_test

production:
  <<: *default
  database: template_production
  username: template_username
  password: <%= ENV['DATABASE_PASSWORD'] %>
